version: "3.8"
services:
  serve-compass-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - non-prod-serve-compass
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - non-prod-serve-compass
    environment:
      POSTGRES_USER: ${DATABASE_USER_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE_USER_NAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - non-prod-serve-compass
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
networks:
  non-prod-serve-compass:
    external: true
